# Aumenta a memória RAM alocada para o Gradle
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# Habilita o suporte moderno do AndroidX e Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Ignora o aviso de compatibilidade com o SDK 34
android.suppressUnsupportedCompileSdk=34

# Otimizações para o build não travar no Windows
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true